// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_Cities")]
    public partial class ArCities
    {
        public ArCities()
        {
            ArProperties = new HashSet<ArProperties>();
            ArStates = new HashSet<ArStates>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("status")]
        public bool? Status { get; set; }
        [Column("country_id")]
        public int? CountryId { get; set; }

        [ForeignKey("CountryId")]
        [InverseProperty("ArCities")]
        public virtual ArCountries Country { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<ArProperties> ArProperties { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<ArStates> ArStates { get; set; }
    }
}