// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_property_images")]
    public partial class ArPropertyImages
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("property_id")]
        public int? PropertyId { get; set; }
        [Column("added_by_user")]
        [StringLength(255)]
        public string AddedByUser { get; set; }
        [Column("image")]
        public string Image { get; set; }
        [Column("created", TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("AddedByUser")]
        [InverseProperty("ArPropertyImages")]
        public virtual ArUsers AddedByUserNavigation { get; set; }
        [ForeignKey("PropertyId")]
        [InverseProperty("ArPropertyImages")]
        public virtual ArProperties Property { get; set; }
    }
}