// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_property_reviews")]
    public partial class ArPropertyReviews
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("property_id")]
        public int? PropertyId { get; set; }
        [Column("review_by_user")]
        [StringLength(255)]
        public string ReviewByUser { get; set; }
        [Column("booking_id")]
        public int? BookingId { get; set; }
        [Column("comment")]
        public string Comment { get; set; }
        [Column("rating")]
        public byte? Rating { get; set; }
        [Column("created", TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column("modified", TypeName = "datetime")]
        public DateTime? Modified { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("BookingId")]
        [InverseProperty("ArPropertyReviews")]
        public virtual ArBookings Booking { get; set; }
        [ForeignKey("PropertyId")]
        [InverseProperty("ArPropertyReviews")]
        public virtual ArProperties Property { get; set; }
        [ForeignKey("ReviewByUser")]
        [InverseProperty("ArPropertyReviews")]
        public virtual ArUsers ReviewByUserNavigation { get; set; }
    }
}