// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_properties")]
    public partial class ArProperties
    {
        public ArProperties()
        {
            ArBookings = new HashSet<ArBookings>();
            ArDisputes = new HashSet<ArDisputes>();
            ArPropertyImages = new HashSet<ArPropertyImages>();
            ArPropertyReviews = new HashSet<ArPropertyReviews>();
            ArTransactions = new HashSet<ArTransactions>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("user_id")]
        [StringLength(255)]
        public string UserId { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("property_type_id")]
        public int? PropertyTypeId { get; set; }
        [Column("room_type_id")]
        public int? RoomTypeId { get; set; }
        [Column("category_id")]
        public int? CategoryId { get; set; }
        [Column("subcategory_id")]
        public int? SubcategoryId { get; set; }
        [Column("country_id")]
        public int? CountryId { get; set; }
        [Column("state_id")]
        public int? StateId { get; set; }
        [Column("city_id")]
        public int? CityId { get; set; }
        [Column("address")]
        public string Address { get; set; }
        [Column("latitude")]
        [StringLength(50)]
        public string Latitude { get; set; }
        [Column("longitude")]
        [StringLength(50)]
        public string Longitude { get; set; }
        [Column("bedroom_count")]
        public byte? BedroomCount { get; set; }
        [Column("bed_count")]
        public byte? BedCount { get; set; }
        [Column("bathroom_count")]
        public byte? BathroomCount { get; set; }
        [Column("accomodates_count")]
        public byte? AccomodatesCount { get; set; }
        [Column("availability_type")]
        public bool? AvailabilityType { get; set; }
        [Column("start_date", TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column("end_date", TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column("price", TypeName = "decimal(10, 2)")]
        public decimal? Price { get; set; }
        [Column("currency_id")]
        public int? CurrencyId { get; set; }
        [Column("price_type")]
        public byte? PriceType { get; set; }
        [Column("minimum_stay")]
        [StringLength(10)]
        public string MinimumStay { get; set; }
        [Column("minimum_stay_type")]
        public byte? MinimumStayType { get; set; }
        [Column("refund_type")]
        public bool? RefundType { get; set; }
        [Column("created", TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column("modified", TypeName = "datetime")]
        public DateTime? Modified { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        public string Url { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("ArProperties")]
        public virtual ArCategories Category { get; set; }
        [ForeignKey("CityId")]
        [InverseProperty("ArProperties")]
        public virtual ArCities City { get; set; }
        [ForeignKey("CountryId")]
        [InverseProperty("ArProperties")]
        public virtual ArCountries Country { get; set; }
        [ForeignKey("CurrencyId")]
        [InverseProperty("ArProperties")]
        public virtual ArCurrencies Currency { get; set; }
        [ForeignKey("PropertyTypeId")]
        [InverseProperty("ArProperties")]
        public virtual ArPropertyType PropertyType { get; set; }
        [ForeignKey("RoomTypeId")]
        [InverseProperty("ArProperties")]
        public virtual ArRoomType RoomType { get; set; }
        [ForeignKey("StateId")]
        [InverseProperty("ArProperties")]
        public virtual ArStates State { get; set; }
        [ForeignKey("SubcategoryId")]
        [InverseProperty("ArProperties")]
        public virtual ArSubcategories Subcategory { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("ArProperties")]
        public virtual ArUsers User { get; set; }
        [InverseProperty("Property")]
        public virtual ICollection<ArBookings> ArBookings { get; set; }
        [InverseProperty("Property")]
        public virtual ICollection<ArDisputes> ArDisputes { get; set; }
        [InverseProperty("Property")]
        public virtual ICollection<ArPropertyImages> ArPropertyImages { get; set; }
        [InverseProperty("Property")]
        public virtual ICollection<ArPropertyReviews> ArPropertyReviews { get; set; }
        [InverseProperty("Property")]
        public virtual ICollection<ArTransactions> ArTransactions { get; set; }
    }
}