// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_states")]
    public partial class ArStates
    {
        public ArStates()
        {
            ArProperties = new HashSet<ArProperties>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("city_id")]
        public int? CityId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("code")]
        [StringLength(5)]
        public string Code { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("CityId")]
        [InverseProperty("ArStates")]
        public virtual ArCities City { get; set; }
        [InverseProperty("State")]
        public virtual ICollection<ArProperties> ArProperties { get; set; }
    }
}