// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_subcategories")]
    public partial class ArSubcategories
    {
        public ArSubcategories()
        {
            ArProperties = new HashSet<ArProperties>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("category_id")]
        public int? CategoryId { get; set; }
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Column("created", TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column("modified", TypeName = "datetime")]
        public DateTime? Modified { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("ArSubcategories")]
        public virtual ArCategories Category { get; set; }
        [InverseProperty("Subcategory")]
        public virtual ICollection<ArProperties> ArProperties { get; set; }
    }
}