// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace API_Airbnb.Data.Models
{
    [Table("ar_users")]
    public partial class ArUsers:IdentityUser
    {
        public ArUsers()
        {
            ArBookings = new HashSet<ArBookings>();
            ArDisputes = new HashSet<ArDisputes>();
            ArProperties = new HashSet<ArProperties>();
            ArPropertyImages = new HashSet<ArPropertyImages>();
            ArPropertyReviews = new HashSet<ArPropertyReviews>();
            ArTransactions = new HashSet<ArTransactions>();
        }

        [Key]
        [Column("id")]
        [StringLength(255)]
        public override string Id { get; set; }
        [Column("first_name")]
        public string FirstName { get; set; }
        [Column("last_name")]
        public string LastName { get; set; }
        //[Column("email")]
        //public string Email { get; set; }
        //[Column("password")]
        //public string Password { get; set; }
        [Column("user_type")]
        public bool? UserType { get; set; }
        [Column("date_of_birth", TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column("facebook_id")]
        public string FacebookId { get; set; }
        [Column("twitter_id")]
        public string TwitterId { get; set; }
        [Column("about")]
        public string About { get; set; }
        [Column("recieve_coupon")]
        public bool? RecieveCoupon { get; set; }
        [Column("created", TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column("modified", TypeName = "datetime")]
        public DateTime? Modified { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<ArBookings> ArBookings { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ArDisputes> ArDisputes { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ArProperties> ArProperties { get; set; }
        [InverseProperty("AddedByUserNavigation")]
        public virtual ICollection<ArPropertyImages> ArPropertyImages { get; set; }
        [InverseProperty("ReviewByUserNavigation")]
        public virtual ICollection<ArPropertyReviews> ArPropertyReviews { get; set; }
        [InverseProperty("Reciever")]
        public virtual ICollection<ArTransactions> ArTransactions { get; set; }
    }
}